# Generated by Django 4.0.1 on 2022-01-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rollNumber', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
